alanc: testAlanError348.alan:1:1: error: expected 'source', but found identifier
